dist: xenial
language: minimal
sudo: required

addons:
  apt:
    update: true
    packages:
      - texlive-latex-recommended
      - texlive-xetex
      - texlive-math-extra
      - pgf
      - texlive-luatex
      - biber
      - latexmk
      - fonts-noto
      - fonts-noto-mono
      - fonts-lmodern
      
script:
- latexmk -f -lualatex -interaction=nonstopmode example.tex
