dist: xenial
sudo: required
dist: trusty
before_install:
- sudo wget -O texlive.tar.gz http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
- tar -zxvf texlive.tar.gz
- cd install-tl-*
- echo "selected_scheme scheme-full" > profile
- sudo ./install-tl -profile profile
- cd ..
- sudo wget -O /usr/bin/latexmk http://mirrors.ctan.org/support/latexmk/latexmk.pl
- sudo chmod +x /usr/bin/latexmk
script:
- latexmk -lualatex -interaction=nonstopmode example.tex
