dist: xenial
language: minimal
sudo: required

addons:
  apt:
    update: true
    packages:
      - texlive-latex-recommended
      - texlive-luatex
      - latexmk

script:
- latexmk -lualatex -interaction=nonstopmode example.tex
