dist: xenial
language: minimal
sudo: required

addons:
  apt:
    update: true
    source:
      - sourceline: 'ppa:universe'
    packages:
      - texlive-lua

script:
- latexmk -pdflua -interaction=nonstopmode example.tex
